apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: booking-service
  namespace: volvo-powersync
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - volvo-powersync
  selector:
    matchLabels:
      app: booking-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
