apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: volvo-powersync
type: Opaque
stringData:
  POSTGRES_DB: powersync
  POSTGRES_USER: powersync
  POSTGRES_PASSWORD: powersync
